linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - govet
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
issues:
  exclude-rules:
    - path: test
      linters:
        - funlen
        - lll
        - dupl
        - gosec
        - scopelint
    - path: internal/app/di
      linters:
        - govet
    - path: internal/app/di/internal/definitions
      linters:
        - funlen
        - revive
        - stylecheck
    - path: internal\\app\\di\\internal\\definitions
      linters:
        - funlen
        - revive
        - stylecheck
