version: "2"

# There are some disabled linters that can be enabled later. I disabled it after migrating to golangci-lint v2.

linters:
  disable:
    - govet
    - staticcheck
    - gocognit
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - err113
    - forbidigo
    #- funlen
    - gochecknoinits
    #- gocognit
    #- goconst
    - gocritic
    - gocyclo
    #- godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    #- nestif
    #- noctx
    #- nolintlint
    - prealloc
    #- revive
    - rowserrcheck
    #- staticcheck
    - thelper
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gosec
          - govet
          - lll
          - scopelint
        path: test
      - linters:
          - govet
        path: internal/app/di
      - linters:
          - funlen
          - revive
          - staticcheck
        path: internal/app/di/internal/definitions
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
