build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - go-scrutinizer-run
    tests:
      environment:
        go:
          version: 'go1.16'
      project_setup:
        override:
          - go mod download
      tests:
        override:
          - command: go test -v $(go list ./...) -coverpkg .,./decode,./encode -coverprofile=cover.out
            coverage:
              file: 'cover.out'
              format: 'go-cc'

filter:
  excluded_paths:
    - '*/*test.go'
    - 'test/*'

checks:
  go: true
