on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux"]
        goarch: ["amd64", "386", "arm64", "arm", "mips", "mips64"]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.21
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz"
          project_path: "./cmd/gameap-daemon"
          binary_name: "gameap-daemon"
          extra_files: README.md
