on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "windows"]
        goarch: ["amd64", "386", "arm64", "arm", "mips", "mips64"]
        exclude:
          - goarch: "mips"
            goos: windows
          - goarch: "mips64"
            goos: windows
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date --iso-8601=seconds) >> ${GITHUB_ENV}


      - uses: wangyoucao577/go-release-action@v1.21
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.18.9.linux-amd64.tar.gz"
          md5sum: false
          overwrite: true
          project_path: "./cmd/gameap-daemon"
          ldflags: -X "github.com/gameap/daemon/internal/app/build.Version=${{ env.APP_VERSION }}" -X "github.com/gameap/daemon/internal/app/build.BuildDate=${{ env.BUILD_TIME }}"
          binary_name: "gameap-daemon"
          extra_files: README.md
